apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: spiceroute
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: us-central1-docker.pkg.dev/YOUR_PROJECT/spiceroute/gateway:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_DSN
              valueFrom:
                secretKeyRef:
                  name: spiceroute-secret
                  key: DB_DSN
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: spiceroute
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
