apiVersion: apps/v1
kind: Deployment
metadata:
  name: vector
  namespace: spiceroute
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vector
  template:
    metadata:
      labels:
        app: vector
    spec:
      containers:
        - name: vector
          image: us-central1-docker.pkg.dev/YOUR_PROJECT/spiceroute/vector:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_DSN
              valueFrom:
                secretKeyRef:
                  name: spiceroute-secret
                  key: DB_DSN
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: spiceroute-secret
                  key: OPENAI_API_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: vector
  namespace: spiceroute
spec:
  selector:
    app: vector
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
